In [1]:
import sys

print(sys.executable)
print(sys.version)

c:\Users\PC\Documents\Kiva-Data-Cleaning-porEddySantana\.venv\Scripts\python.exe
3.13.15 (tags/v3.13.15:4061bc4, Aug  5 2026, 13:05:39) [MSC v.1944 64 bit (AMD64)]

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../Data/kiva_loans_42304_rows.csv")

In [4]:
df.head()

,id,funded_amount,loan_amount,activity,sector,use,country_code,country,region,currency,partner_id,posted_time,disbursed_time,funded_time,term_in_months,lender_count,tags,borrower_genders,repayment_interval,date
0,1175609,525.0,525.0,Personal Medical Expenses,Health,to buy medicines for her son’s treatment at th...,TJ,Tajikistan,Kanibadam,TJS,100.0,2016-10-27 04:54:27+00:00,2016-10-04 07:00:00+00:00,2016-11-05 02:14:03+00:00,14.0,18,#Health and Sanitation,female,monthly,2016-10-27
1,1056732,350.0,350.0,Butcher Shop,Food,to buy a refrigerator for his butcher shop,MX,Mexico,Ecatepec,MXN,294.0,2016-04-19 15:55:26+00:00,2016-03-31 07:00:00+00:00,2016-04-25 20:14:08+00:00,8.0,10,"#Elderly, #First Loan, #Health and Sanitation,...",male,monthly,2016-04-19
2,773348,225.0,225.0,Food,Food,to buy more raw ingredients for making food sn...,PH,Philippines,"Plaridel-Unidos, Plaridel, Misamis Occidental",PHP,126.0,2014-09-23 08:53:49+00:00,2014-09-19 07:00:00+00:00,2014-10-04 14:33:45+00:00,11.0,9,"volunteer_pick, volunteer_like, #Woman Owned Biz",female,irregular,2014-09-23
3,1076908,325.0,325.0,Farming,Agriculture,to purchase sacks of fertilizer,PH,Philippines,"Pagadian City, Zamboanga del Sur",PHP,126.0,2016-05-27 08:40:46+00:00,2016-05-10 07:00:00+00:00,2016-06-02 12:04:03+00:00,7.0,7,user_favorite,female,irregular,2016-05-27
4,680170,500.0,500.0,Poultry,Agriculture,To purchase more broiler chicks,ZW,Zimbabwe,Nyanga,USD,305.0,2014-03-06 10:29:22+00:00,2014-03-05 08:00:00+00:00,2014-04-02 01:31:55+00:00,8.0,11,"#Woman Owned Biz, #Parent, #Low-profit FP",female,irregular,2014-03-06

In [5]:
df.shape

(42308, 20)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 42308 entries, 0 to 42307
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  42308 non-null  int64
 1   funded_amount       42308 non-null  float64
 2   loan_amount         42308 non-null  float64
 3   activity            42308 non-null  str
 4   sector              42308 non-null  str
 5   use                 42308 non-null  str
 6   country_code        42308 non-null  str
 7   country             42308 non-null  str
 8   region              42308 non-null  str
 9   currency            42308 non-null  str
 10  partner_id          42308 non-null  float64
 11  posted_time         42308 non-null  str
 12  disbursed_time      42308 non-null  str
 13  funded_time         42308 non-null  str
 14  term_in_months      42308 non-null  float64
 15  lender_count        42308 non-null  int64
 16  tags                42308 non-null  str
 17  borrower_genders    42308 non-null  str
 18  repayment_interval  42308 non-null  str
 19  date                42308 non-null  str
dtypes: float64(4), int64(2), str(14)
memory usage: 6.5 MB

In [7]:
df.columns

Index(['id', 'funded_amount', 'loan_amount', 'activity', 'sector', 'use',
       'country_code', 'country', 'region', 'currency', 'partner_id',
       'posted_time', 'disbursed_time', 'funded_time', 'term_in_months',
       'lender_count', 'tags', 'borrower_genders', 'repayment_interval',
       'date'],
      dtype='str')

In [8]:
df.isnull().sum()

id                    0
funded_amount         0
loan_amount           0
activity              0
sector                0
use                   0
country_code          0
country               0
region                0
currency              0
partner_id            0
posted_time           0
disbursed_time        0
funded_time           0
term_in_months        0
lender_count          0
tags                  0
borrower_genders      0
repayment_interval    0
date                  0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.nunique()

id                    42308
funded_amount           328
loan_amount             328
activity                157
sector                   15
use                   32547
country_code             74
country                  74
region                 4438
currency                 62
partner_id              267
posted_time           42294
disbursed_time         1379
funded_time           40991
term_in_months          100
lender_count            255
tags                  12447
borrower_genders       1360
repayment_interval        3
date                   1275
dtype: int64

In [11]:
df["repayment_interval"].value_counts()

repayment_interval
monthly      22980
irregular    15009
bullet        4319
Name: count, dtype: int64

In [12]:
df[["funded_amount", "loan_amount"]].describe()

       funded_amount   loan_amount
count   42308.000000  42308.000000
mean      844.327905    844.327905
std      1081.746992   1081.746992
min        25.000000     25.000000
25%       300.000000    300.000000
50%       500.000000    500.000000
75%      1000.000000   1000.000000
max     50000.000000  50000.000000

In [13]:
(df["funded_amount"] == df["loan_amount"]).all()

np.True_

In [14]:
df[["posted_time", "disbursed_time", "funded_time", "date"]].head()

,posted_time,disbursed_time,funded_time,date
0,2016-10-27 04:54:27+00:00,2016-10-04 07:00:00+00:00,2016-11-05 02:14:03+00:00,2016-10-27
1,2016-04-19 15:55:26+00:00,2016-03-31 07:00:00+00:00,2016-04-25 20:14:08+00:00,2016-04-19
2,2014-09-23 08:53:49+00:00,2014-09-19 07:00:00+00:00,2014-10-04 14:33:45+00:00,2014-09-23
3,2016-05-27 08:40:46+00:00,2016-05-10 07:00:00+00:00,2016-06-02 12:04:03+00:00,2016-05-27
4,2014-03-06 10:29:22+00:00,2014-03-05 08:00:00+00:00,2014-04-02 01:31:55+00:00,2014-03-06

In [15]:
df[["posted_time", "disbursed_time", "funded_time", "date"]].dtypes

posted_time       str
disbursed_time    str
funded_time       str
date              str
dtype: object

In [16]:
df[["posted_time", "disbursed_time", "funded_time", "date"]].isna().sum()

posted_time       0
disbursed_time    0
funded_time       0
date              0
dtype: int64

In [17]:
df[["posted_time", "disbursed_time", "funded_time", "date"]].head(10)

,posted_time,disbursed_time,funded_time,date
0,2016-10-27 04:54:27+00:00,2016-10-04 07:00:00+00:00,2016-11-05 02:14:03+00:00,2016-10-27
1,2016-04-19 15:55:26+00:00,2016-03-31 07:00:00+00:00,2016-04-25 20:14:08+00:00,2016-04-19
2,2014-09-23 08:53:49+00:00,2014-09-19 07:00:00+00:00,2014-10-04 14:33:45+00:00,2014-09-23
3,2016-05-27 08:40:46+00:00,2016-05-10 07:00:00+00:00,2016-06-02 12:04:03+00:00,2016-05-27
4,2014-03-06 10:29:22+00:00,2014-03-05 08:00:00+00:00,2014-04-02 01:31:55+00:00,2014-03-06
5,2016-04-06 22:26:23+00:00,2016-03-09 08:00:00+00:00,2016-04-11 18:26:06+00:00,2016-04-06
6,2014-08-26 15:32:13+00:00,2014-08-23 07:00:00+00:00,2014-09-18 21:03:02+00:00,2014-08-26
7,2016-07-20 08:32:06+00:00,2016-06-30 07:00:00+00:00,2016-07-29 15:26:51+00:00,2016-07-20
8,2014-05-21 21:16:50+00:00,2014-04-30 07:00:00+00:00,2014-07-02 15:58:33+00:00,2014-05-21
9,2016-12-30 08:26:30+00:00,2016-12-29 08:00:00+00:00,2017-01-30 03:16:43+00:00,2016-12-30

In [18]:
df["posted_time"] = pd.to_datetime(df["posted_time"])
df["disbursed_time"] = pd.to_datetime(df["disbursed_time"])
df["funded_time"] = pd.to_datetime(df["funded_time"])
df["date"] = pd.to_datetime(df["date"])

In [19]:
df[["posted_time", "disbursed_time", "funded_time", "date"]].dtypes

posted_time       datetime64[us, UTC]
disbursed_time    datetime64[us, UTC]
funded_time       datetime64[us, UTC]
date                   datetime64[us]
dtype: object

In [20]:
df[["posted_time", "disbursed_time", "funded_time", "date"]].dtypes

posted_time       datetime64[us, UTC]
disbursed_time    datetime64[us, UTC]
funded_time       datetime64[us, UTC]
date                   datetime64[us]
dtype: object

In [21]:
df.dtypes

id                                  int64
funded_amount                     float64
loan_amount                       float64
activity                              str
sector                                str
use                                   str
country_code                          str
country                               str
region                                str
currency                              str
partner_id                        float64
posted_time           datetime64[us, UTC]
disbursed_time        datetime64[us, UTC]
funded_time           datetime64[us, UTC]
term_in_months                    float64
lender_count                        int64
tags                                  str
borrower_genders                      str
repayment_interval                    str
date                       datetime64[us]
dtype: object

In [22]:
df.dtypes.value_counts()

str                    10
float64                 4
datetime64[us, UTC]     3
int64                   2
datetime64[us]          1
Name: count, dtype: int64

In [23]:
df["sector"].value_counts()

sector
Agriculture       11861
Food               8106
Retail             7158
Services           2870
Personal Use       2577
Education          2403
Clothing           2041
Housing            2028
Transportation      982
Arts                768
Health              677
Construction        397
Manufacturing       342
Wholesale            49
Entertainment        49
Name: count, dtype: int64

In [24]:
df["sector"].str.strip().ne(df["sector"]).sum()

np.int64(0)

In [25]:
df["sector"].value_counts()

sector
Agriculture       11861
Food               8106
Retail             7158
Services           2870
Personal Use       2577
Education          2403
Clothing           2041
Housing            2028
Transportation      982
Arts                768
Health              677
Construction        397
Manufacturing       342
Wholesale            49
Entertainment        49
Name: count, dtype: int64

In [26]:
df["country"].value_counts()

country
Philippines                         9234
Kenya                               4757
Cambodia                            2537
Pakistan                            2074
Tajikistan                          1576
                                    ...
Congo                                  8
South Sudan                            5
Saint Vincent and the Grenadines       4
Senegal                                4
Turkey                                 3
Name: count, Length: 74, dtype: int64

In [27]:
df["country"].str.strip().ne(df["country"]).sum()

np.int64(0)

In [28]:
df["activity"].str.strip().ne(df["activity"]).sum()

np.int64(0)

In [29]:
df["currency"].value_counts()

currency
PHP    9234
USD    5682
KES    4728
KHR    2163
PKR    2074
       ...
BZD       8
THB       7
SSP       5
XCD       4
TRY       3
Name: count, Length: 62, dtype: int64

In [30]:
df["currency"].str.strip().ne(df["currency"]).sum()

np.int64(0)

In [31]:
df["repayment_interval"].value_counts()

repayment_interval
monthly      22980
irregular    15009
bullet        4319
Name: count, dtype: int64

In [32]:
df["repayment_interval"].str.strip().ne(df["repayment_interval"]).sum()

np.int64(0)

In [33]:
df["repayment_interval"].str.strip().ne(df["repayment_interval"]).sum()

np.int64(0)

In [34]:
df[["funded_amount", "loan_amount", "term_in_months", "lender_count"]].describe()

       funded_amount   loan_amount  term_in_months  lender_count
count   42308.000000  42308.000000    42308.000000  42308.000000
mean      844.327905    844.327905       14.124255     23.276023
std      1081.746992   1081.746992        8.434400     28.493808
min        25.000000     25.000000        2.000000      1.000000
25%       300.000000    300.000000        8.000000      8.000000
50%       500.000000    500.000000       14.000000     15.000000
75%      1000.000000   1000.000000       14.000000     28.000000
max     50000.000000  50000.000000      148.000000   1410.000000

In [35]:
(df[["funded_amount", "loan_amount", "term_in_months", "lender_count"]] <= 0).sum()

funded_amount     0
loan_amount       0
term_in_months    0
lender_count      0
dtype: int64

In [36]:
df["term_in_months"].sort_values(ascending=False).head(10)

10957    148.0
15992    146.0
4662     145.0
39639    143.0
31305    142.0
26829    131.0
12799    131.0
13433    125.0
7873     122.0
37511    122.0
Name: term_in_months, dtype: float64

In [37]:
(df["term_in_months"] > 60).sum()

np.int64(222)

In [38]:
df.loc[df["term_in_months"] > 60, "activity"].value_counts().head(15)

activity
Higher education costs            133
Home Energy                        26
Health                             20
Agriculture                        11
Farming                             7
Primary/secondary school costs      4
Taxi                                3
Beauty Salon                        2
Food Production/Sales               2
Pigs                                2
Bakery                              2
Clothing                            1
Personal Medical Expenses           1
Home Products Sales                 1
Home Appliances                     1
Name: count, dtype: int64

In [39]:
df.loc[df["term_in_months"] > 60, "term_in_months"].value_counts().sort_index()

term_in_months
61.0      3
62.0     40
63.0     16
64.0      1
65.0      1
67.0      4
68.0     15
69.0      3
70.0      5
72.0      9
73.0     10
74.0     19
75.0     15
76.0      3
77.0      2
79.0      3
80.0      4
81.0      3
82.0      2
83.0      1
85.0      3
86.0     12
87.0      3
88.0      1
90.0      3
91.0      3
92.0      2
94.0      3
97.0      3
98.0      5
100.0     1
101.0     4
104.0     1
106.0     1
107.0     1
113.0     1
118.0     1
122.0     7
125.0     1
131.0     2
142.0     1
143.0     1
145.0     1
146.0     1
148.0     1
Name: count, dtype: int64

In [40]:
df["lender_count"].sort_values(ascending=False).head(10)

33285    1410
21901    1330
21564    1240
19190     994
35724     726
23597     616
2507      419
2186      356
22868     355
28378     343
Name: lender_count, dtype: int64

In [41]:
(df["lender_count"] > 100).sum()

np.int64(925)

In [42]:
df.loc[df["lender_count"] > 100, ["loan_amount", "lender_count"]].describe()

        loan_amount  lender_count
count    925.000000    925.000000
mean    4911.135135    146.228108
std     3263.088083     87.882675
min     2575.000000    101.000000
25%     3500.000000    111.000000
50%     4450.000000    127.000000
75%     5450.000000    155.000000
max    50000.000000   1410.000000

In [43]:
df[["loan_amount", "lender_count"]].corr()

              loan_amount  lender_count
loan_amount      1.000000      0.874909
lender_count     0.874909      1.000000

In [44]:
df.dtypes

id                                  int64
funded_amount                     float64
loan_amount                       float64
activity                              str
sector                                str
use                                   str
country_code                          str
country                               str
region                                str
currency                              str
partner_id                        float64
posted_time           datetime64[us, UTC]
disbursed_time        datetime64[us, UTC]
funded_time           datetime64[us, UTC]
term_in_months                    float64
lender_count                        int64
tags                                  str
borrower_genders                      str
repayment_interval                    str
date                       datetime64[us]
dtype: object

In [45]:
df["partner_id"].value_counts().head(10)

partner_id
145.0    6173
199.0    1287
311.0    1241
156.0    1120
177.0    1043
247.0    1038
125.0    1015
58.0      880
138.0     871
245.0     783
Name: count, dtype: int64

In [46]:
df["partner_id"].dropna().mod(1).ne(0).sum()

np.int64(0)

In [47]:
df["partner_id"].isna().sum()

np.int64(0)

In [48]:
df["partner_id"] = df["partner_id"].astype("int64")

In [49]:
df["partner_id"] = df["partner_id"].astype("int64")

In [50]:
df["partner_id"].dtype

dtype('int64')

In [51]:
df["term_in_months"].dropna().mod(1).ne(0).sum()

np.int64(0)

In [52]:
df["term_in_months"] = df["term_in_months"].astype("int64")

In [53]:
df["term_in_months"].dtype

dtype('int64')

In [54]:
df["id"].duplicated().sum()

np.int64(0)

In [55]:
df["id"].nunique()

42308

In [56]:
df["use"].str.strip().ne(df["use"]).sum()

np.int64(2806)

In [57]:
df.loc[
    df["use"].str.strip().ne(df["use"]),
    "use"
].head(20)

0      to buy medicines for her son’s treatment at th...
38     to buy a water purification machine for the fa...
48                       to pay her university tuition.
57     to purchase a refrigerator which she wants to ...
58     to purchase consumer items for her husband's b...
68                            to buy pigs for breeding.
73     To buy a water filter to provide safe drinking...
74     to purchase food items, wheat flour, cooking o...
100                                       to buy a cow.
121    to purchase hybrid seeds and fertilizer to imp...
156     to buy more merchandise to sell during this f...
157    to purchase more equipment for his photography...
164                             to pay university fees.
172     To pay for grocery items, toiletries and beve...
214                                    to purchase pigs
225    to service and paint his car, in order to make...
228    to buy supplies for her small fast-food counte...
234                                      to buy sweets.
237    to purchase fertilizers for her Mexican yam cr...
254    for the fixation of her husband's fuel truck s...
Name: use, dtype: str

In [58]:
df["use"] = df["use"].str.strip()

In [59]:
columnas_texto = [
    "use",
    "country_code",
    "region",
    "tags",
    "borrower_genders"
]

for columna in columnas_texto:
    espacios = df[columna].str.strip().ne(df[columna]).sum()
    print(f"{columna}: {espacios}")

use: 0
country_code: 0
region: 51
tags: 0
borrower_genders: 0

In [60]:
df.loc[
    df["region"].str.strip().ne(df["region"]),
    "region"
].value_counts()

region
Battambang province, Kam Rieng district               10
Kampong Thom Province, Santok District                 7
Oroquieta-Misamis Occidental                           6
San Cristobal Totonicapan                              4
Battambang Province, Banon District                    4
Takeo Province, Kiri Vong District                     2
SINDANGAN - GUSA, CALATUNAN, SINDANGAN, ZAMBOANGA      2
Phnom Penh, Dongkor District                           2
Kampong Speu Province, Borset District                 2
Localidad San Rafael, San Juan Bautista Tuxtepec,      1
N'Tentoukoro                                           1
Tominian                                               1
Fana                                                   1
Sasar Village, Thma Andoeurk Commune, Chetr Borei      1
Loulouni                                               1
Koury                                                  1
Chhoung Preal Village, Toek Hot Commune, Rolea Pe      1
Pagadian - Alindahaw, Tukuran                          1
Dangassa                                               1
Troncones y La Corriente, Ciudad Valles, San Luis      1
Sindangan-Binuangan                                    1
Name: count, dtype: int64

In [61]:
df["region"] = df["region"].str.strip()

In [62]:
# 1. Comprobar valores nulos
print("Valores nulos:")
print(df[["posted_time", "disbursed_time", "funded_time", "date"]].isna().sum())

# 2. Comprobar fechas futuras
ahora = pd.Timestamp.now(tz="UTC")

print("\nFechas futuras:")
print("posted_time:", (df["posted_time"] > ahora).sum())
print("disbursed_time:", (df["disbursed_time"] > ahora).sum())
print("funded_time:", (df["funded_time"] > ahora).sum())

# 3. Comprobar orden lógico de las fechas
print("\nOrden de fechas:")

print(
    "disbursed_time anterior a posted_time:",
    (df["disbursed_time"] < df["posted_time"]).sum()
)

print(
    "funded_time anterior a posted_time:",
    (df["funded_time"] < df["posted_time"]).sum()
)

print(
    "funded_time anterior a disbursed_time:",
    (df["funded_time"] < df["disbursed_time"]).sum()
)

Valores nulos:
posted_time       0
disbursed_time    0
funded_time       0
date              0
dtype: int64

Fechas futuras:
posted_time: 0
disbursed_time: 0
funded_time: 0

Orden de fechas:
disbursed_time anterior a posted_time: 39952
funded_time anterior a posted_time: 0
funded_time anterior a disbursed_time: 1304

In [63]:
print("Ejemplos: disbursed_time anterior a posted_time")
print(
    df.loc[
        df["disbursed_time"] < df["posted_time"],
        ["id", "posted_time", "disbursed_time", "funded_time"]
    ].head(5)
)

print("\nEjemplos: funded_time anterior a disbursed_time")
print(
    df.loc[
        df["funded_time"] < df["disbursed_time"],
        ["id", "posted_time", "disbursed_time", "funded_time"]
    ].head(5)
)

Ejemplos: disbursed_time anterior a posted_time
        id               posted_time            disbursed_time  \
0  1175609 2016-10-27 04:54:27+00:00 2016-10-04 07:00:00+00:00
1  1056732 2016-04-19 15:55:26+00:00 2016-03-31 07:00:00+00:00
2   773348 2014-09-23 08:53:49+00:00 2014-09-19 07:00:00+00:00
3  1076908 2016-05-27 08:40:46+00:00 2016-05-10 07:00:00+00:00
4   680170 2014-03-06 10:29:22+00:00 2014-03-05 08:00:00+00:00

                funded_time
0 2016-11-05 02:14:03+00:00
1 2016-04-25 20:14:08+00:00
2 2014-10-04 14:33:45+00:00
3 2016-06-02 12:04:03+00:00
4 2014-04-02 01:31:55+00:00

Ejemplos: funded_time anterior a disbursed_time
          id               posted_time            disbursed_time  \
76   1164527 2016-10-07 14:08:41+00:00 2016-11-30 08:00:00+00:00
89   1222128 2017-01-18 10:22:21+00:00 2017-01-26 08:00:00+00:00
121  1252639 2017-03-08 07:45:01+00:00 2017-04-01 07:00:00+00:00
125  1261584 2017-03-20 10:55:14+00:00 2017-04-15 07:00:00+00:00
140   973552 2015-11-04 11:35:11+00:00 2015-11-17 08:00:00+00:00

                  funded_time
76  2016-10-20 18:16:44+00:00
89  2017-01-21 14:11:38+00:00
121 2017-03-28 14:58:02+00:00
125 2017-03-25 09:03:46+00:00
140 2015-11-06 06:41:13+00:00

In [64]:
print("Valores nulos:")
print(df["country_code"].isna().sum())

print("\nValores únicos:")
print(df["country_code"].nunique())

print("\nCódigos de país:")
print(df["country_code"].value_counts().head(20))

print("\nEspacios al inicio o final:")
print(df["country_code"].str.strip().ne(df["country_code"]).sum())

Valores nulos:
0

Valores únicos:
74

Códigos de país:
country_code
PH    9234
KE    4757
KH    2537
PK    2074
TJ    1576
CO    1458
PE    1424
SV    1313
UG    1309
EC    1005
PY     880
VN     846
NI     830
IN     713
BO     653
AM     643
PS     630
WS     614
GT     601
NG     579
Name: count, dtype: int64

Espacios al inicio o final:
0

In [65]:
print("TAGS")
print("Valores nulos:", df["tags"].isna().sum())
print("Valores vacíos:", (df["tags"].str.strip() == "").sum())
print("Ejemplos:")
print(df["tags"].dropna().head(10))

print("\n" + "=" * 50 + "\n")

print("BORROWER_GENDERS")
print("Valores nulos:", df["borrower_genders"].isna().sum())
print("Valores vacíos:", (df["borrower_genders"].str.strip() == "").sum())
print("Valores únicos:")
print(df["borrower_genders"].value_counts().head(15))

TAGS
Valores nulos: 0
Valores vacíos: 0
Ejemplos:
0                               #Health and Sanitation
1    #Elderly, #First Loan, #Health and Sanitation,...
2     volunteer_pick, volunteer_like, #Woman Owned Biz
3                                        user_favorite
4            #Woman Owned Biz, #Parent, #Low-profit FP
5                                        user_favorite
6    volunteer_pick, volunteer_like, #Repeat Borrow...
7                                             #Elderly
8                  #First Loan, #Health and Sanitation
9                         user_favorite, user_favorite
Name: tags, dtype: str

==================================================

BORROWER_GENDERS
Valores nulos: 0
Valores vacíos: 0
Valores únicos:
borrower_genders
female                                                                                                                                    26408
male                                                                                                                                       8371
female, female, female                                                                                                                      843
female, female                                                                                                                              809
female, female, female, female                                                                                                              663
female, female, female, female, female                                                                                                      628
female, female, female, female, female, female                                                                                              171
female, female, female, female, female, female, female, female, female, female                                                              140
female, female, female, female, female, female, female, female                                                                              135
female, female, female, female, female, female, female                                                                                      133
male, female                                                                                                                                117
female, male                                                                                                                                105
female, female, female, female, female, female, female, female, female                                                                       96
female, female, female, female, female, female, female, female, female, female, female, female, female, female, female, female, female       88
female, female, female, female, female, female, female, female, female, female, female, female, female, female, female                       85
Name: count, dtype: int64

In [66]:
print("Países y códigos de país:")
print(
    df.groupby(["country", "country_code"])
      .size()
      .sort_values(ascending=False)
      .head(30)
)

Países y códigos de país:
country       country_code
Philippines   PH              9234
Kenya         KE              4757
Cambodia      KH              2537
Pakistan      PK              2074
Tajikistan    TJ              1576
Colombia      CO              1458
Peru          PE              1424
El Salvador   SV              1313
Uganda        UG              1309
Ecuador       EC              1005
Paraguay      PY               880
Vietnam       VN               846
Nicaragua     NI               830
India         IN               713
Bolivia       BO               653
Armenia       AM               643
Palestine     PS               630
Samoa         WS               614
Guatemala     GT               601
Nigeria       NG               579
Lebanon       LB               552
Honduras      HN               518
Kyrgyzstan    KG               484
Mexico        MX               421
Tanzania      TZ               401
Indonesia     ID               391
Sierra Leone  SL               382
Togo          TG               379
Mali          ML               368
Ghana         GH               355
dtype: int64

In [67]:
print("Filas totales:", len(df))
print("IDs únicos:", df["id"].nunique())
print("IDs duplicados:", df["id"].duplicated().sum())

Filas totales: 42308
IDs únicos: 42308
IDs duplicados: 0

In [68]:
# ==========================================
# BLOQUE: VALIDACIÓN DE VARIABLES NUMÉRICAS
# ==========================================

columnas_numericas = [
    "funded_amount",
    "loan_amount",
    "term_in_months",
    "lender_count",
    "partner_id"
]

print("1. TIPOS DE DATOS")
print(df[columnas_numericas].dtypes)

print("\n" + "=" * 60)

print("2. VALORES NULOS")
print(df[columnas_numericas].isna().sum())

print("\n" + "=" * 60)

print("3. VALORES MENORES O IGUALES A CERO")
print((df[columnas_numericas] <= 0).sum())

print("\n" + "=" * 60)

print("4. ESTADÍSTICAS DESCRIPTIVAS")
print(df[columnas_numericas].describe())

print("\n" + "=" * 60)

print("5. funded_amount Y loan_amount")
print("¿Son iguales en todas las filas?:",
      (df["funded_amount"] == df["loan_amount"]).all())

print("Diferencias entre funded_amount y loan_amount:",
      (df["funded_amount"] != df["loan_amount"]).sum())

print("\n" + "=" * 60)

print("6. partner_id: valores decimales")
print(
    df["partner_id"]
      .dropna()
      .mod(1)
      .ne(0)
      .sum()
)

print("\n" + "=" * 60)

print("7. term_in_months: valores decimales")
print(
    df["term_in_months"]
      .dropna()
      .mod(1)
      .ne(0)
      .sum()
)

print("\n" + "=" * 60)

print("8. VALORES EXTREMOS")

print("\nTerm_in_months - 10 valores más altos:")
print(
    df["term_in_months"]
      .sort_values(ascending=False)
      .head(10)
      .to_list()
)

print("\nLender_count - 10 valores más altos:")
print(
    df["lender_count"]
      .sort_values(ascending=False)
      .head(10)
      .to_list()
)

print("\nLoan_amount - 10 valores más altos:")
print(
    df["loan_amount"]
      .sort_values(ascending=False)
      .head(10)
      .to_list()
)

1. TIPOS DE DATOS
funded_amount     float64
loan_amount       float64
term_in_months      int64
lender_count        int64
partner_id          int64
dtype: object

============================================================
2. VALORES NULOS
funded_amount     0
loan_amount       0
term_in_months    0
lender_count      0
partner_id        0
dtype: int64

============================================================
3. VALORES MENORES O IGUALES A CERO
funded_amount     0
loan_amount       0
term_in_months    0
lender_count      0
partner_id        0
dtype: int64

============================================================
4. ESTADÍSTICAS DESCRIPTIVAS
       funded_amount   loan_amount  term_in_months  lender_count    partner_id
count   42308.000000  42308.000000    42308.000000  42308.000000  42308.000000
mean      844.327905    844.327905       14.124255     23.276023    184.002104
std      1081.746992   1081.746992        8.434400     28.493808     99.689027
min        25.000000     25.000000        2.000000      1.000000      9.000000
25%       300.000000    300.000000        8.000000      8.000000    126.000000
50%       500.000000    500.000000       14.000000     15.000000    154.000000
75%      1000.000000   1000.000000       14.000000     28.000000    222.000000
max     50000.000000  50000.000000      148.000000   1410.000000    528.000000

============================================================
5. funded_amount Y loan_amount
¿Son iguales en todas las filas?: True
Diferencias entre funded_amount y loan_amount: 0

============================================================
6. partner_id: valores decimales
0

============================================================
7. term_in_months: valores decimales
0

============================================================
8. VALORES EXTREMOS

Term_in_months - 10 valores más altos:
[148, 146, 145, 143, 142, 131, 131, 125, 122, 122]

Lender_count - 10 valores más altos:
[1410, 1330, 1240, 994, 726, 616, 419, 356, 355, 343]

Loan_amount - 10 valores más altos:
[50000.0, 49925.0, 40000.0, 40000.0, 25000.0, 25000.0, 20000.0, 12375.0, 11775.0, 10100.0]

In [69]:
# ==========================================
# BLOQUE: AUDITORÍA DE VARIABLES DE TEXTO
# ==========================================

columnas_texto = [
    "activity",
    "sector",
    "use",
    "country_code",
    "country",
    "region",
    "currency",
    "tags",
    "borrower_genders",
    "repayment_interval"
]

print("1. VALORES NULOS")
print(df[columnas_texto].isna().sum())

print("\n" + "=" * 70)

print("2. CADENAS VACÍAS")
print(
    (df[columnas_texto].apply(lambda col: col.str.strip() == "")).sum()
)

print("\n" + "=" * 70)

print("3. ESPACIOS AL INICIO O FINAL")

for columna in columnas_texto:
    espacios = df[columna].str.strip().ne(df[columna]).sum()
    print(f"{columna}: {espacios}")

print("\n" + "=" * 70)

print("4. CANTIDAD DE VALORES ÚNICOS")

print(df[columnas_texto].nunique().sort_values())

print("\n" + "=" * 70)

print("5. VALORES MÁS FRECUENTES")

for columna in columnas_texto:
    print(f"\n--- {columna} ---")
    print(df[columna].value_counts().head(5))

1. VALORES NULOS
activity              0
sector                0
use                   0
country_code          0
country               0
region                0
currency              0
tags                  0
borrower_genders      0
repayment_interval    0
dtype: int64

======================================================================
2. CADENAS VACÍAS
activity              0
sector                0
use                   0
country_code          0
country               0
region                0
currency              0
tags                  0
borrower_genders      0
repayment_interval    0
dtype: int64

======================================================================
3. ESPACIOS AL INICIO O FINAL
activity: 0
sector: 0
use: 0
country_code: 0
country: 0
region: 0
currency: 0
tags: 0
borrower_genders: 0
repayment_interval: 0

======================================================================
4. CANTIDAD DE VALORES ÚNICOS
repayment_interval        3
sector                   15
currency                 62
country                  74
country_code             74
activity                157
borrower_genders       1360
region                 4438
tags                  12447
use                   32158
dtype: int64

======================================================================
5. VALORES MÁS FRECUENTES

--- activity ---
activity
Farming                      4811
General Store                3615
Personal Housing Expenses    1926
Pigs                         1706
Higher education costs       1619
Name: count, dtype: int64

--- sector ---
sector
Agriculture     11861
Food             8106
Retail           7158
Services         2870
Personal Use     2577
Name: count, dtype: int64

--- use ---
use
to buy a water filter to provide safe drinking water for their family.    442
to buy a water filter to provide safe drinking water for her family.      355
To buy a water filter to provide safe drinking water for their family.    214
to build a sanitary toilet for her family                                 150
to build a sanitary toilet for her family.                                148
Name: count, dtype: int64

--- country_code ---
country_code
PH    9234
KE    4757
KH    2537
PK    2074
TJ    1576
Name: count, dtype: int64

--- country ---
country
Philippines    9234
Kenya          4757
Cambodia       2537
Pakistan       2074
Tajikistan     1576
Name: count, dtype: int64

--- region ---
region
Kaduna           561
Lahore           516
Rawalpindi       356
Kisii            277
Dar es Salaam    276
Name: count, dtype: int64

--- currency ---
currency
PHP    9234
USD    5682
KES    4728
KHR    2163
PKR    2074
Name: count, dtype: int64

--- tags ---
tags
user_favorite                2418
#Parent, #Woman Owned Biz    1408
#Woman Owned Biz             1087
#Parent                       857
#Elderly                      604
Name: count, dtype: int64

--- borrower_genders ---
borrower_genders
female                            26408
male                               8371
female, female, female              843
female, female                      809
female, female, female, female      663
Name: count, dtype: int64

--- repayment_interval ---
repayment_interval
monthly      22980
irregular    15009
bullet        4319
Name: count, dtype: int64

In [70]:
# ==========================================
# BLOQUE: TRANSFORMACIONES Y ESTADO DE LIMPIEZA
# ==========================================

# 1. Normalizar espacios exteriores en textos
df["use"] = df["use"].str.strip()
df["region"] = df["region"].str.strip()

# 2. Convertir fechas a datetime
df["posted_time"] = pd.to_datetime(df["posted_time"])
df["disbursed_time"] = pd.to_datetime(df["disbursed_time"])
df["funded_time"] = pd.to_datetime(df["funded_time"])
df["date"] = pd.to_datetime(df["date"])

# 3. Convertir identificadores y plazos a enteros
df["partner_id"] = df["partner_id"].astype("int64")
df["term_in_months"] = df["term_in_months"].astype("int64")

# 4. Mostrar los tipos finales
print("TIPOS DE DATOS DESPUÉS DE LA LIMPIEZA")
print(df.dtypes)

print("\n" + "=" * 70)

# 5. Comprobar tamaño del dataset
print("TAMAÑO FINAL")
print("Filas:", df.shape[0])
print("Columnas:", df.shape[1])

print("\n" + "=" * 70)

# 6. Comprobar nulos
print("VALORES NULOS")
print(df.isna().sum().sum())

print("\n" + "=" * 70)

# 7. Comprobar filas duplicadas
print("FILAS DUPLICADAS")
print(df.duplicated().sum())

print("\n" + "=" * 70)

# 8. Comprobar IDs duplicados
print("IDs DUPLICADOS")
print(df["id"].duplicated().sum())

TIPOS DE DATOS DESPUÉS DE LA LIMPIEZA
id                                  int64
funded_amount                     float64
loan_amount                       float64
activity                              str
sector                                str
use                                   str
country_code                          str
country                               str
region                                str
currency                              str
partner_id                          int64
posted_time           datetime64[us, UTC]
disbursed_time        datetime64[us, UTC]
funded_time           datetime64[us, UTC]
term_in_months                      int64
lender_count                        int64
tags                                  str
borrower_genders                      str
repayment_interval                    str
date                       datetime64[us]
dtype: object

======================================================================
TAMAÑO FINAL
Filas: 42308
Columnas: 20

======================================================================
VALORES NULOS
0

======================================================================
FILAS DUPLICADAS
0

======================================================================
IDs DUPLICADOS
0

In [71]:
# ==========================================
# VALIDACIÓN FINAL DEL DATASET LIMPIO
# ==========================================

print("VALIDACIÓN FINAL")
print("=" * 70)

# 1. Tamaño
print("\n1. TAMAÑO")
print("Filas:", len(df))
print("Columnas:", len(df.columns))

# 2. Duplicados
print("\n2. DUPLICADOS")
print("Filas duplicadas:", df.duplicated().sum())
print("IDs duplicados:", df["id"].duplicated().sum())

# 3. Valores nulos
print("\n3. VALORES NULOS")
print("Total de valores nulos:", df.isna().sum().sum())

# 4. Valores numéricos no válidos
print("\n4. VALORES NUMÉRICOS NO VÁLIDOS")

print(
    "funded_amount <= 0:",
    (df["funded_amount"] <= 0).sum()
)

print(
    "loan_amount <= 0:",
    (df["loan_amount"] <= 0).sum()
)

print(
    "term_in_months <= 0:",
    (df["term_in_months"] <= 0).sum()
)

print(
    "lender_count <= 0:",
    (df["lender_count"] <= 0).sum()
)

print(
    "partner_id <= 0:",
    (df["partner_id"] <= 0).sum()
)

# 5. Consistencia de importes
print("\n5. CONSISTENCIA DE IMPORTES")

print(
    "funded_amount != loan_amount:",
    (df["funded_amount"] != df["loan_amount"]).sum()
)

# 6. Fechas
print("\n6. VALIDACIÓN DE FECHAS")

print(
    "posted_time nulos:",
    df["posted_time"].isna().sum()
)

print(
    "disbursed_time nulos:",
    df["disbursed_time"].isna().sum()
)

print(
    "funded_time nulos:",
    df["funded_time"].isna().sum()
)

print(
    "date nulos:",
    df["date"].isna().sum()
)

ahora = pd.Timestamp.now(tz="UTC")

print(
    "posted_time futuras:",
    (df["posted_time"] > ahora).sum()
)

print(
    "disbursed_time futuras:",
    (df["disbursed_time"] > ahora).sum()
)

print(
    "funded_time futuras:",
    (df["funded_time"] > ahora).sum()
)

# 7. Country / country_code
print("\n7. PAÍSES")

print("Países únicos:", df["country"].nunique())
print("Códigos únicos:", df["country_code"].nunique())

# 8. Repayment interval
print("\n8. REPAYMENT INTERVAL")
print(df["repayment_interval"].value_counts())

# 9. Tipos importantes
print("\n9. TIPOS DE DATOS")

print("id:", df["id"].dtype)
print("partner_id:", df["partner_id"].dtype)
print("term_in_months:", df["term_in_months"].dtype)
print("lender_count:", df["lender_count"].dtype)
print("posted_time:", df["posted_time"].dtype)
print("disbursed_time:", df["disbursed_time"].dtype)
print("funded_time:", df["funded_time"].dtype)
print("date:", df["date"].dtype)

print("\n" + "=" * 70)
print("FIN DE LA VALIDACIÓN")

VALIDACIÓN FINAL
======================================================================

1. TAMAÑO
Filas: 42308
Columnas: 20

2. DUPLICADOS
Filas duplicadas: 0
IDs duplicados: 0

3. VALORES NULOS
Total de valores nulos: 0

4. VALORES NUMÉRICOS NO VÁLIDOS
funded_amount <= 0: 0
loan_amount <= 0: 0
term_in_months <= 0: 0
lender_count <= 0: 0
partner_id <= 0: 0

5. CONSISTENCIA DE IMPORTES
funded_amount != loan_amount: 0

6. VALIDACIÓN DE FECHAS
posted_time nulos: 0
disbursed_time nulos: 0
funded_time nulos: 0
date nulos: 0
posted_time futuras: 0
disbursed_time futuras: 0
funded_time futuras: 0

7. PAÍSES
Países únicos: 74
Códigos únicos: 74

8. REPAYMENT INTERVAL
repayment_interval
monthly      22980
irregular    15009
bullet        4319
Name: count, dtype: int64

9. TIPOS DE DATOS
id: int64
partner_id: int64
term_in_months: int64
lender_count: int64
posted_time: datetime64[us, UTC]
disbursed_time: datetime64[us, UTC]
funded_time: datetime64[us, UTC]
date: datetime64[us]

======================================================================
FIN DE LA VALIDACIÓN

In [72]:
# ==========================================
# EXPORTACIÓN DEL DATASET LIMPIO
# ==========================================

ruta_salida = "../Data/kiva_loans_clean.csv"

df.to_csv(
    ruta_salida,
    index=False
)

print("Dataset limpio exportado correctamente.")
print("Archivo:", ruta_salida)
print("Filas:", len(df))
print("Columnas:", len(df.columns))

Dataset limpio exportado correctamente.
Archivo: ../Data/kiva_loans_clean.csv
Filas: 42308
Columnas: 20

In [73]:
# ==========================================
# VALIDACIÓN DEL ARCHIVO EXPORTADO
# ==========================================

df_check = pd.read_csv("../Data/kiva_loans_clean.csv")

print("VALIDACIÓN DEL CSV EXPORTADO")
print("=" * 70)

print("\n1. TAMAÑO")
print("Filas:", df_check.shape[0])
print("Columnas:", df_check.shape[1])

print("\n" + "=" * 70)

print("2. COLUMNAS")
print(df_check.columns.tolist())

print("\n" + "=" * 70)

print("3. VALORES NULOS")
print("Total:", df_check.isna().sum().sum())

print("\n" + "=" * 70)

print("4. FILAS DUPLICADAS")
print(df_check.duplicated().sum())

print("\n" + "=" * 70)

print("5. IDs DUPLICADOS")
print(df_check["id"].duplicated().sum())

print("\n" + "=" * 70)

print("6. COMPARACIÓN CON EL DATAFRAME LIMPIO")

print("Mismo número de filas:",
      len(df_check) == len(df))

print("Mismo número de columnas:",
      len(df_check.columns) == len(df.columns))

print("Mismas columnas:",
      df_check.columns.tolist() == df.columns.tolist())

print("\n" + "=" * 70)

print("7. PRIMERAS FILAS DEL ARCHIVO EXPORTADO")
print(df_check.head())

VALIDACIÓN DEL CSV EXPORTADO
======================================================================

1. TAMAÑO
Filas: 42308
Columnas: 20

======================================================================
2. COLUMNAS
['id', 'funded_amount', 'loan_amount', 'activity', 'sector', 'use', 'country_code', 'country', 'region', 'currency', 'partner_id', 'posted_time', 'disbursed_time', 'funded_time', 'term_in_months', 'lender_count', 'tags', 'borrower_genders', 'repayment_interval', 'date']

======================================================================
3. VALORES NULOS
Total: 0

======================================================================
4. FILAS DUPLICADAS
0

======================================================================
5. IDs DUPLICADOS
0

======================================================================
6. COMPARACIÓN CON EL DATAFRAME LIMPIO
Mismo número de filas: True
Mismo número de columnas: True
Mismas columnas: True

======================================================================
7. PRIMERAS FILAS DEL ARCHIVO EXPORTADO
        id  funded_amount  loan_amount                   activity  \
0  1175609          525.0        525.0  Personal Medical Expenses
1  1056732          350.0        350.0               Butcher Shop
2   773348          225.0        225.0                       Food
3  1076908          325.0        325.0                    Farming
4   680170          500.0        500.0                    Poultry

        sector                                                use  \
0       Health  to buy medicines for her son’s treatment at th...
1         Food         to buy a refrigerator for his butcher shop
2         Food  to buy more raw ingredients for making food sn...
3  Agriculture                    to purchase sacks of fertilizer
4  Agriculture                    To purchase more broiler chicks

  country_code      country                                         region  \
0           TJ   Tajikistan                                      Kanibadam
1           MX       Mexico                                       Ecatepec
2           PH  Philippines  Plaridel-Unidos, Plaridel, Misamis Occidental
3           PH  Philippines               Pagadian City, Zamboanga del Sur
4           ZW     Zimbabwe                                         Nyanga

  currency  partner_id                posted_time             disbursed_time  \
0      TJS         100  2016-10-27 04:54:27+00:00  2016-10-04 07:00:00+00:00
1      MXN         294  2016-04-19 15:55:26+00:00  2016-03-31 07:00:00+00:00
2      PHP         126  2014-09-23 08:53:49+00:00  2014-09-19 07:00:00+00:00
3      PHP         126  2016-05-27 08:40:46+00:00  2016-05-10 07:00:00+00:00
4      USD         305  2014-03-06 10:29:22+00:00  2014-03-05 08:00:00+00:00

                 funded_time  term_in_months  lender_count  \
0  2016-11-05 02:14:03+00:00              14            18
1  2016-04-25 20:14:08+00:00               8            10
2  2014-10-04 14:33:45+00:00              11             9
3  2016-06-02 12:04:03+00:00               7             7
4  2014-04-02 01:31:55+00:00               8            11

                                                tags borrower_genders  \
0                             #Health and Sanitation           female
1  #Elderly, #First Loan, #Health and Sanitation,...             male
2   volunteer_pick, volunteer_like, #Woman Owned Biz           female
3                                      user_favorite           female
4          #Woman Owned Biz, #Parent, #Low-profit FP           female

  repayment_interval        date
0            monthly  2016-10-27
1            monthly  2016-04-19
2          irregular  2014-09-23
3          irregular  2016-05-27
4          irregular  2014-03-06

## Resumen de la limpieza

Durante el proceso de limpieza y validación se realizaron las siguientes comprobaciones y transformaciones:

- Se revisó la estructura inicial del dataset y sus tipos de datos.
- Se comprobaron valores nulos y cadenas vacías.
- Se verificaron filas duplicadas y duplicados en la columna `id`.
- Las columnas `posted_time`, `disbursed_time`, `funded_time` y `date` se convirtieron a formato `datetime`.
- `partner_id` y `term_in_months` se convirtieron a tipo entero.
- Se eliminaron espacios al inicio y al final de los campos `use` y `region`.
- Se comprobó la consistencia entre `country` y `country_code`.
- Se revisaron los valores de `funded_amount`, `loan_amount`, `term_in_months` y `lender_count`.
- Se verificaron valores extremos sin eliminar registros cuando no existía evidencia suficiente de que fueran errores.
- Se comprobó que `funded_amount` y `loan_amount` coinciden en todos los registros.
- Las columnas `tags` y `borrower_genders` se conservaron porque contienen información múltiple dentro de una misma celda.
- No se eliminaron filas del dataset.

### Resultado final

El dataset limpio contiene:

- **42.308 registros**
- **20 columnas**
- **0 valores nulos**
- **0 filas duplicadas**
- **0 IDs duplicados**

El dataset limpio se exportó como `kiva_loans_clean.csv`.

In [74]:
# ==========================================
# DATASET FINAL PARA LA ENTREGA
# ==========================================

df_clean = df.copy()

print("Dataset final preparado.")
print("Filas:", df_clean.shape[0])
print("Columnas:", df_clean.shape[1])

Dataset final preparado.
Filas: 42308
Columnas: 20

In [75]:
# ==========================================
# VALIDACIÓN DEL DATASET FINAL
# ==========================================

print("VALIDACIÓN DEL DATASET FINAL")
print("=" * 60)

print("\nTamaño:")
print("Filas:", len(df_clean))
print("Columnas:", len(df_clean.columns))

print("\nValores nulos:")
print(df_clean.isna().sum().sum())

print("\nFilas duplicadas:")
print(df_clean.duplicated().sum())

print("\nIDs duplicados:")
print(df_clean["id"].duplicated().sum())

print("\nValores no válidos:")
print("funded_amount <= 0:",
      (df_clean["funded_amount"] <= 0).sum())

print("loan_amount <= 0:",
      (df_clean["loan_amount"] <= 0).sum())

print("term_in_months <= 0:",
      (df_clean["term_in_months"] <= 0).sum())

print("lender_count <= 0:",
      (df_clean["lender_count"] <= 0).sum())

print("\nConsistencia de importes:")
print(
    "funded_amount != loan_amount:",
    (df_clean["funded_amount"] != df_clean["loan_amount"]).sum()
)

print("\nValidación completada.")

VALIDACIÓN DEL DATASET FINAL
============================================================

Tamaño:
Filas: 42308
Columnas: 20

Valores nulos:
0

Filas duplicadas:
0

IDs duplicados:
0

Valores no válidos:
funded_amount <= 0: 0
loan_amount <= 0: 0
term_in_months <= 0: 0
lender_count <= 0: 0

Consistencia de importes:
funded_amount != loan_amount: 0

Validación completada.

In [76]:
# ==========================================
# EXPORTACIÓN DEL DATASET FINAL
# ==========================================

ruta_salida = "../Data/kiva_loans_clean.csv"

df_clean.to_csv(
    ruta_salida,
    index=False
)

print("Dataset final exportado correctamente.")
print("Archivo:", ruta_salida)
print("Filas:", len(df_clean))
print("Columnas:", len(df_clean.columns))

Dataset final exportado correctamente.
Archivo: ../Data/kiva_loans_clean.csv
Filas: 42308
Columnas: 20

In [77]:
# ==========================================
# COMPROBACIÓN FINAL DEL ARCHIVO CSV
# ==========================================

df_final = pd.read_csv("../Data/kiva_loans_clean.csv")

print("COMPROBACIÓN FINAL DEL CSV")
print("=" * 60)

print("\nTamaño:")
print("Filas:", df_final.shape[0])
print("Columnas:", df_final.shape[1])

print("\nValores nulos:")
print(df_final.isna().sum().sum())

print("\nFilas duplicadas:")
print(df_final.duplicated().sum())

print("\nIDs duplicados:")
print(df_final["id"].duplicated().sum())

print("\nColumnas:")
print(df_final.columns.tolist())

print("\n¿Mismo número de filas que df_clean?:",
      len(df_final) == len(df_clean))

print("¿Mismo número de columnas?:",
      len(df_final.columns) == len(df_clean.columns))

print("\nPrimeras filas:")
print(df_final.head())

print("\n" + "=" * 60)
print("COMPROBACIÓN FINALIZADA")

COMPROBACIÓN FINAL DEL CSV
============================================================

Tamaño:
Filas: 42308
Columnas: 20

Valores nulos:
0

Filas duplicadas:
0

IDs duplicados:
0

Columnas:
['id', 'funded_amount', 'loan_amount', 'activity', 'sector', 'use', 'country_code', 'country', 'region', 'currency', 'partner_id', 'posted_time', 'disbursed_time', 'funded_time', 'term_in_months', 'lender_count', 'tags', 'borrower_genders', 'repayment_interval', 'date']

¿Mismo número de filas que df_clean?: True
¿Mismo número de columnas?: True

Primeras filas:
        id  funded_amount  loan_amount                   activity  \
0  1175609          525.0        525.0  Personal Medical Expenses
1  1056732          350.0        350.0               Butcher Shop
2   773348          225.0        225.0                       Food
3  1076908          325.0        325.0                    Farming
4   680170          500.0        500.0                    Poultry

        sector                                                use  \
0       Health  to buy medicines for her son’s treatment at th...
1         Food         to buy a refrigerator for his butcher shop
2         Food  to buy more raw ingredients for making food sn...
3  Agriculture                    to purchase sacks of fertilizer
4  Agriculture                    To purchase more broiler chicks

  country_code      country                                         region  \
0           TJ   Tajikistan                                      Kanibadam
1           MX       Mexico                                       Ecatepec
2           PH  Philippines  Plaridel-Unidos, Plaridel, Misamis Occidental
3           PH  Philippines               Pagadian City, Zamboanga del Sur
4           ZW     Zimbabwe                                         Nyanga

  currency  partner_id                posted_time             disbursed_time  \
0      TJS         100  2016-10-27 04:54:27+00:00  2016-10-04 07:00:00+00:00
1      MXN         294  2016-04-19 15:55:26+00:00  2016-03-31 07:00:00+00:00
2      PHP         126  2014-09-23 08:53:49+00:00  2014-09-19 07:00:00+00:00
3      PHP         126  2016-05-27 08:40:46+00:00  2016-05-10 07:00:00+00:00
4      USD         305  2014-03-06 10:29:22+00:00  2014-03-05 08:00:00+00:00

                 funded_time  term_in_months  lender_count  \
0  2016-11-05 02:14:03+00:00              14            18
1  2016-04-25 20:14:08+00:00               8            10
2  2014-10-04 14:33:45+00:00              11             9
3  2016-06-02 12:04:03+00:00               7             7
4  2014-04-02 01:31:55+00:00               8            11

                                                tags borrower_genders  \
0                             #Health and Sanitation           female
1  #Elderly, #First Loan, #Health and Sanitation,...             male
2   volunteer_pick, volunteer_like, #Woman Owned Biz           female
3                                      user_favorite           female
4          #Woman Owned Biz, #Parent, #Low-profit FP           female

  repayment_interval        date
0            monthly  2016-10-27
1            monthly  2016-04-19
2          irregular  2014-09-23
3          irregular  2016-05-27
4          irregular  2014-03-06

============================================================
COMPROBACIÓN FINALIZADA

In [78]:
# ============================================================
# DATASET FINAL - LIMPIEZA, VALIDACIÓN Y EXPORTACIÓN
# ============================================================

# Crear una copia del dataset limpio
df_clean = df.copy()

# ------------------------------------------------------------
# 1. Validaciones generales
# ------------------------------------------------------------

print("VALIDACIÓN DEL DATASET FINAL")
print("=" * 50)

print(f"Filas: {df_clean.shape[0]}")
print(f"Columnas: {df_clean.shape[1]}")
print(f"Valores nulos: {df_clean.isnull().sum().sum()}")
print(f"Filas duplicadas: {df_clean.duplicated().sum()}")
print(f"IDs duplicados: {df_clean['id'].duplicated().sum()}")

# ------------------------------------------------------------
# 2. Validaciones numéricas
# ------------------------------------------------------------

print("\nVALIDACIÓN DE VALORES NUMÉRICOS")
print("=" * 50)

print("funded_amount <= 0:",
      (df_clean["funded_amount"] <= 0).sum())

print("loan_amount <= 0:",
      (df_clean["loan_amount"] <= 0).sum())

print("term_in_months <= 0:",
      (df_clean["term_in_months"] <= 0).sum())

print("lender_count <= 0:",
      (df_clean["lender_count"] <= 0).sum())

print("funded_amount != loan_amount:",
      (df_clean["funded_amount"] != df_clean["loan_amount"]).sum())

# ------------------------------------------------------------
# 3. Exportación
# ------------------------------------------------------------

ruta_salida = "../Data/kiva_loans_clean.csv"

df_clean.to_csv(ruta_salida, index=False)

print("\nDATASET EXPORTADO")
print("=" * 50)
print(f"Archivo: {ruta_salida}")
print(f"Filas: {df_clean.shape[0]}")
print(f"Columnas: {df_clean.shape[1]}")

# ------------------------------------------------------------
# 4. Comprobación del archivo exportado
# ------------------------------------------------------------

df_final = pd.read_csv(ruta_salida)

print("\nCOMPROBACIÓN DEL ARCHIVO EXPORTADO")
print("=" * 50)

print(f"Filas: {df_final.shape[0]}")
print(f"Columnas: {df_final.shape[1]}")
print(f"Valores nulos: {df_final.isnull().sum().sum()}")
print(f"Filas duplicadas: {df_final.duplicated().sum()}")
print(f"IDs duplicados: {df_final['id'].duplicated().sum()}")

print("\n¿Mismo número de filas y columnas?:",
      df_final.shape == df_clean.shape)

print("\nProceso finalizado correctamente.")

VALIDACIÓN DEL DATASET FINAL
==================================================
Filas: 42308
Columnas: 20
Valores nulos: 0
Filas duplicadas: 0
IDs duplicados: 0

VALIDACIÓN DE VALORES NUMÉRICOS
==================================================
funded_amount <= 0: 0
loan_amount <= 0: 0
term_in_months <= 0: 0
lender_count <= 0: 0
funded_amount != loan_amount: 0

DATASET EXPORTADO
==================================================
Archivo: ../Data/kiva_loans_clean.csv
Filas: 42308
Columnas: 20

COMPROBACIÓN DEL ARCHIVO EXPORTADO
==================================================
Filas: 42308
Columnas: 20
Valores nulos: 0
Filas duplicadas: 0
IDs duplicados: 0

¿Mismo número de filas y columnas?: True

Proceso finalizado correctamente.

In [79]:
# ============================================================
# PROCESO FINAL: DATASET LIMPIO, VALIDACIÓN Y EXPORTACIÓN
# ============================================================

# Creamos una copia definitiva del dataset trabajado
df_clean = df.copy()

print("PROCESAMIENTO Y LIMPIEZA DE DATOS - RESULTADO FINAL")
print("=" * 60)

# ------------------------------------------------------------
# 1. INFORMACIÓN GENERAL
# ------------------------------------------------------------

print("\n1. INFORMACIÓN GENERAL")
print("-" * 40)

print(f"Filas: {df_clean.shape[0]}")
print(f"Columnas: {df_clean.shape[1]}")

# ------------------------------------------------------------
# 2. VALORES FALTANTES Y DUPLICADOS
# ------------------------------------------------------------

print("\n2. VALORES FALTANTES Y DUPLICADOS")
print("-" * 40)

print(f"Valores nulos totales: {df_clean.isnull().sum().sum()}")
print(f"Filas duplicadas: {df_clean.duplicated().sum()}")
print(f"IDs duplicados: {df_clean['id'].duplicated().sum()}")

# ------------------------------------------------------------
# 3. VALIDACIÓN DE VALORES NUMÉRICOS
# ------------------------------------------------------------

print("\n3. VALIDACIÓN DE VALORES NUMÉRICOS")
print("-" * 40)

print(
    "funded_amount <= 0:",
    (df_clean["funded_amount"] <= 0).sum()
)

print(
    "loan_amount <= 0:",
    (df_clean["loan_amount"] <= 0).sum()
)

print(
    "term_in_months <= 0:",
    (df_clean["term_in_months"] <= 0).sum()
)

print(
    "lender_count <= 0:",
    (df_clean["lender_count"] <= 0).sum()
)

print(
    "funded_amount != loan_amount:",
    (df_clean["funded_amount"] != df_clean["loan_amount"]).sum()
)

# ------------------------------------------------------------
# 4. VALIDACIÓN DE FECHAS
# ------------------------------------------------------------

print("\n4. VALIDACIÓN DE FECHAS")
print("-" * 40)

print(
    "Valores nulos en fechas:",
    df_clean[
        ["posted_time", "disbursed_time", "funded_time", "date"]
    ].isnull().sum().sum()
)

print(
    "Fechas futuras:",
    (
        df_clean["date"] > pd.Timestamp.now()
    ).sum()
)

# ------------------------------------------------------------
# 5. VALIDACIÓN DE CATEGORÍAS
# ------------------------------------------------------------

print("\n5. VALIDACIÓN DE CATEGORÍAS")
print("-" * 40)

print(f"Países diferentes: {df_clean['country'].nunique()}")
print(f"Códigos de país: {df_clean['country_code'].nunique()}")
print(
    f"Intervalos de pago: "
    f"{df_clean['repayment_interval'].nunique()}"
)
print(f"Sectores: {df_clean['sector'].nunique()}")

# ------------------------------------------------------------
# 6. TIPOS DE DATOS
# ------------------------------------------------------------

print("\n6. TIPOS DE DATOS")
print("-" * 40)

print(df_clean.dtypes)

# ------------------------------------------------------------
# 7. EXPORTACIÓN DEL DATASET LIMPIO
# ------------------------------------------------------------

ruta_salida = "../Data/kiva_loans_clean.csv"

df_clean.to_csv(
    ruta_salida,
    index=False
)

print("\n7. EXPORTACIÓN")
print("-" * 40)

print(f"Dataset exportado en: {ruta_salida}")

# ------------------------------------------------------------
# 8. COMPROBACIÓN DEL ARCHIVO EXPORTADO
# ------------------------------------------------------------

df_final = pd.read_csv(ruta_salida)

print("\n8. COMPROBACIÓN DEL ARCHIVO EXPORTADO")
print("-" * 40)

print(f"Filas: {df_final.shape[0]}")
print(f"Columnas: {df_final.shape[1]}")
print(f"Valores nulos: {df_final.isnull().sum().sum()}")
print(f"Filas duplicadas: {df_final.duplicated().sum()}")
print(f"IDs duplicados: {df_final['id'].duplicated().sum()}")

print(
    "¿Coinciden las dimensiones?:",
    df_final.shape == df_clean.shape
)

print(
    "¿Coinciden las columnas?:",
    list(df_final.columns) == list(df_clean.columns)
)

# ------------------------------------------------------------
# 9. RESULTADO FINAL
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("PROCESO FINALIZADO CORRECTAMENTE")
print("=" * 60)

print(f"Dataset final: {df_final.shape[0]} filas x {df_final.shape[1]} columnas")
print("Archivo generado: kiva_loans_clean.csv")

PROCESAMIENTO Y LIMPIEZA DE DATOS - RESULTADO FINAL
============================================================

1. INFORMACIÓN GENERAL
----------------------------------------
Filas: 42308
Columnas: 20

2. VALORES FALTANTES Y DUPLICADOS
----------------------------------------
Valores nulos totales: 0
Filas duplicadas: 0
IDs duplicados: 0

3. VALIDACIÓN DE VALORES NUMÉRICOS
----------------------------------------
funded_amount <= 0: 0
loan_amount <= 0: 0
term_in_months <= 0: 0
lender_count <= 0: 0
funded_amount != loan_amount: 0

4. VALIDACIÓN DE FECHAS
----------------------------------------
Valores nulos en fechas: 0
Fechas futuras: 0

5. VALIDACIÓN DE CATEGORÍAS
----------------------------------------
Países diferentes: 74
Códigos de país: 74
Intervalos de pago: 3
Sectores: 15

6. TIPOS DE DATOS
----------------------------------------
id                                  int64
funded_amount                     float64
loan_amount                       float64
activity                              str
sector                                str
use                                   str
country_code                          str
country                               str
region                                str
currency                              str
partner_id                          int64
posted_time           datetime64[us, UTC]
disbursed_time        datetime64[us, UTC]
funded_time           datetime64[us, UTC]
term_in_months                      int64
lender_count                        int64
tags                                  str
borrower_genders                      str
repayment_interval                    str
date                       datetime64[us]
dtype: object

7. EXPORTACIÓN
----------------------------------------
Dataset exportado en: ../Data/kiva_loans_clean.csv

8. COMPROBACIÓN DEL ARCHIVO EXPORTADO
----------------------------------------
Filas: 42308
Columnas: 20
Valores nulos: 0
Filas duplicadas: 0
IDs duplicados: 0
¿Coinciden las dimensiones?: True
¿Coinciden las columnas?: True

============================================================
PROCESO FINALIZADO CORRECTAMENTE
============================================================
Dataset final: 42308 filas x 20 columnas
Archivo generado: kiva_loans_clean.csv